// Generated by CoffeeScript 1.6.3
(function() {
  var InboxView, MessageCollectionView, OutboxView, ReminderView, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MessageCollectionView = (function(_super) {
    __extends(MessageCollectionView, _super);

    function MessageCollectionView() {
      this.init = __bind(this.init, this);
      this.addOne = __bind(this.addOne, this);
      _ref = MessageCollectionView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MessageCollectionView.prototype.addOne = function(message) {
      this.colleciton.add(message);
      return this.$el.append(new MessageView(message));
    };

    MessageCollectionView.prototype.init = function() {
      return this.collection = new Backbone.Collection();
    };

    return MessageCollectionView;

  })(Backbone.View);

  InboxView = new MessageCollectionView({
    el: document.getElementByClassName('inbox')[0]
  });

  OutboxView = new MessageCollectionView({
    el: document.getElementByClassName('outbox')[0]
  });

  ReminderView = new MessageCollectionView({
    el: document.getElementmentByClassName('reminder')[0]
  });

}).call(this);
