// Generated by CoffeeScript 1.6.3
(function() {
  chrome.app.runtime.onLaunched.addListener(function() {
    return chrome.app.window.create('index.html', {
      'bounds': {
        'width': 400,
        'height': 500
      }
    });
  });

}).call(this);
