// Generated by CoffeeScript 1.6.3
(function() {
  var MessageViewApp, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MessageViewApp = (function(_super) {
    __extends(MessageViewApp, _super);

    function MessageViewApp() {
      this.init = __bind(this.init, this);
      _ref = MessageViewApp.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MessageViewApp.prototype.el = document.getElementByTag('body');

    MessageViewApp.prototype.init = function() {
      return chrome.storage.local.get('messages', function(messages) {
        _.each(messages, function(message) {
          var newMessage;
          newMessage = new Message({
            title: message.title,
            body: message.body,
            tags: message.tags,
            box: message.box
          });
          return $('.' + box).append(new MessageView(newMessage));
        });
      });
    };

    return MessageViewApp;

  })(Backbone.View);

}).call(this);
