// Generated by CoffeeScript 1.6.3
(function() {
  var MessageView, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MessageView = (function(_super) {
    __extends(MessageView, _super);

    function MessageView() {
      this.init = __bind(this.init, this);
      this.render = __bind(this.render, this);
      _ref = MessageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MessageView.prototype.tagName = 'div';

    MessageView.prototype.className = 'message';

    MessageView.prototype.render = function(message) {
      var output, tag, _i, _len, _ref1;
      output = '<div class=\'title\'>{ message.title  }</div>';
      output += '<div class=\'body\'>{ message.body }</div>';
      _ref1 = message.tags;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        tag = _ref1[_i];
        output += '<div class=\'tag\'> { tag } </div>';
      }
      this.$el.append(output);
      return this.$el;
    };

    MessageView.prototype.init = function(message) {
      return this.render(message);
    };

    return MessageView;

  })(Backbone.View);

}).call(this);
